Repository jooby-project/jooby, pull requests merged in 2018-10, with the labels that each got.

#1251 Fix documentation of dependency
  doc/doc/assets-autoprefixer/autoprefixer.md
Labels: documentation

#1242 Prevented filtering of stork executables
  modules/jooby-dist/src/main/resources/assemblies/jooby.stork.xml
Labels: bug, stork

#1233 update README.md of jooby-commons-email
  modules/jooby-commons-email/README.md
Labels: documentation

#1252 update gradle-shadow-plugin
  doc/fatjar.md
Labels: documentation

#1248 add support the Json-b - JSR -367
  doc/doc/parser-and-renderer/parser-and-renderer.md
  doc/doc/yasson/README.md
  modules/jooby-yasson/pom.xml
  modules/jooby-yasson/src/main/java/org/jooby/json/Yasson.java
  modules/jooby-yasson/src/main/java/org/jooby/json/YassonParser.java
  modules/jooby-yasson/src/main/java/org/jooby/json/YassonRenderer.java
  modules/jooby-yasson/src/test/java/org/jooby/json/YassonParserTest.java
  modules/jooby-yasson/src/test/java/org/jooby/json/YassonRendererTest.java
  modules/pom.xml
  pom.xml
Labels: json-b
