Repository jooby-project/jooby, pull requests merged in 2018-02, with the labels that each got.

#1008 upgrade aws
  modules/jooby-bom/pom.xml
  pom.xml
Labels: aws, version-bump

#1012 upgrade caffeine
  modules/jooby-bom/pom.xml
  pom.xml
Labels: caffeine, version-bump

#1015 upgrade rocker
  modules/jooby-bom/pom.xml
  pom.xml
Labels: rocker, version-bump

#1013 upgrade akka
  modules/jooby-bom/pom.xml
  pom.xml
Labels: akka, version-bump

#1016 upgrade jade
  modules/jooby-bom/pom.xml
  pom.xml
Labels: jade, version-bump

#1014 upgrade swagger
  modules/jooby-bom/pom.xml
  pom.xml
Labels: swagger, version-bump

#1024 querydsl upgrade
  pom.xml
Labels: querydsl, version-bump

#1029 jcypher upgrade
  pom.xml
Labels: neo4j, version-bump

#1026 bson4jackson upgrade
  pom.xml
Labels: version-bump

#1027 elasticsearch upgrade
  pom.xml
Labels: elasticsearch, version-bump

#1030 batik upgrade - full coverage build passes
  pom.xml
Labels: assets, version-bump

#1028 neo4j.expire upgrade
  pom.xml
Labels: neo4j, version-bump

#1025 hazelcast upgrade
  pom.xml
Labels: hazelcast, version-bump

#1040 Clarifying the @Local injection documentation & injection error
  doc/req.md
  jooby/src/main/java/org/jooby/internal/mvc/RequestParam.java
  jooby/src/test/java/org/jooby/internal/mvc/RequestParamTest.java
Labels: enhancement

#1041 Updating the Jdbi3 dependency version
  modules/jooby-jdbi3/pom.xml
  pom.xml
Labels: jdbi, version-bump

#1042 Updating AssetMojo to honor the Maven project.baseDir
  modules/jooby-assets/src/main/java/org/jooby/assets/AssetClassLoader.java
  modules/jooby-assets/src/main/java/org/jooby/assets/AssetCompiler.java
  modules/jooby-assets/src/main/java/org/jooby/assets/Assets.java
  modules/jooby-assets/src/test/java/org/jooby/assets/AssetClassLoaderTest.java
  modules/jooby-maven-plugin/src/main/java/org/jooby/AssetMojo.java
Labels: assets, enhancement
