Repository jooby-project/jooby, pull requests merged in 2018-07, with the labels that each got.

#1195 Fix missing flush on Netty context
  modules/coverage-report/src/test/java/org/jooby/issues/Issue1194.java
  modules/jooby-netty/src/main/java/org/jooby/internal/netty/NettyResponse.java
  modules/jooby-netty/src/test/java/org/jooby/internal/netty/NettyResponseTest.java
Labels: netty

#1211 Fix broken module name badges
  modules/jooby-assets-autoprefixer/README.md
  modules/jooby-assets-babel/README.md
  modules/jooby-assets-clean-css/README.md
  modules/jooby-assets-closure-compiler/README.md
  modules/jooby-assets-csslint/README.md
  modules/jooby-assets-jscs/README.md
  modules/jooby-assets-jshint/README.md
  modules/jooby-assets-less/README.md
  modules/jooby-assets-less4j/README.md
  modules/jooby-assets-ng-annotate/README.md
  modules/jooby-assets-requirejs/README.md
  modules/jooby-assets-rollup/README.md
  modules/jooby-assets-sass/README.md
  modules/jooby-assets-svg-sprites/README.md
  modules/jooby-assets-svg-symbol/README.md
  modules/jooby-assets-uglify/README.md
  modules/jooby-assets-yui-compressor/README.md
  modules/jooby-commons-email/README.md
  modules/jooby-gradle-plugin/README.md
  modules/jooby-guava-cache/README.md
  modules/jooby-lang-kotlin/README.md
  modules/jooby-maven-plugin/README.md
  modules/jooby-mongodb-rx/README.md
  modules/jooby-rxjava-jdbc/README.md
Labels: documentation

#1192 Taint analysis
  jooby/src/main/java/org/jooby/Jooby.java
  jooby/src/main/java/org/jooby/internal/RequestImpl.java
  modules/jooby-assets-clean-css/src/test/java/org/jooby/assets/Generator.java
  modules/jooby-assets-svg-sprites/src/main/java/org/jooby/assets/SvgSprites.java
  modules/jooby-assets/src/main/java/org/jooby/internal/assets/AssetWriter.java
  modules/jooby-netty/src/main/java/org/jooby/internal/netty/NettySslContext.java
  modules/jooby-pac4j/src/main/java/org/jooby/internal/pac4j/AuthSerializer.java
  modules/jooby-pac4j2/src/main/java/org/jooby/internal/pac4j2/Pac4jSessionStore.java
  modules/jooby-run/src/main/java/org/jooby/run/Main.java
Labels: tech task
