Repository jooby-project/jooby, pull requests merged in 2018-06, with the labels that each got.

#1119 POM version aggregation
  .gitignore
  modules/coverage-report/pom.xml
  modules/jooby-apitool/pom.xml
  modules/jooby-archetype/pom.xml
  modules/jooby-assets-nodejs/pom.xml
  modules/jooby-assets-sass/pom.xml
  modules/jooby-assets-svg-sprites/pom.xml
  modules/jooby-assets/pom.xml
  modules/jooby-cassandra/pom.xml
  modules/jooby-crash/pom.xml
  modules/jooby-frontend/pom.xml
  modules/jooby-gradle-plugin/pom.xml
  modules/jooby-jdbc/pom.xml
  modules/jooby-lang-kotlin/pom.xml
  modules/jooby-maven-plugin/pom.xml
  modules/jooby-neo4j/pom.xml
  modules/jooby-pac4j2/pom.xml
  modules/jooby-requery/pom.xml
  modules/jooby-whoops/pom.xml
  pom.xml
Labels: tech task

#1130 Adding support for modules with @Provides annotated methods
  jooby/src/main/java/org/jooby/Jooby.java
  jooby/src/test/java/org/jooby/JoobyTest.java
  modules/coverage-report/src/test/java/org/jooby/ModuleProvidesFeature.java
Labels: enhancement

#1146 Parameter expansion in Swagger building applied only to query/form re…
  modules/jooby-apitool/src/main/java/org/jooby/internal/apitool/SwaggerBuilder.java
Labels: apitool, bug, swagger

#1161 cleanup-jooby-hazelcast
  modules/jooby-hazelcast/src/main/java/org/jooby/hazelcast/Hcast.java
  modules/jooby-hazelcast/src/main/java/org/jooby/hazelcast/HcastSessionStore.java
Labels: tech task

#1153 cleanup-jooby-executor
  modules/jooby-executor/src/main/java/org/jooby/exec/Exec.java
Labels: tech task

#1149 Upgrade maven dependencies (next try :-))
  pom.xml
Labels: tech task

#1154 cleanup-jooby-ehcache
  modules/jooby-ehcache/src/main/java/org/jooby/ehcache/EhSessionStore.java
  modules/jooby-ehcache/src/main/java/org/jooby/internal/ehcache/CacheConfigurationBuilder.java
  modules/jooby-ehcache/src/main/java/org/jooby/internal/ehcache/ConfigurationBuilder.java
Labels: tech task

#1155 cleanup-jooby-caffeine
  modules/jooby-caffeine/src/main/java/org/jooby/caffeine/CaffeineCache.java
  modules/jooby-caffeine/src/main/java/org/jooby/caffeine/CaffeineSessionStore.java
Labels: tech task

#1156 cleanup-jooby-couchbase
  modules/jooby-couchbase/src/main/java/org/jooby/couchbase/AsyncDatastore.java
  modules/jooby-couchbase/src/main/java/org/jooby/couchbase/Couchbase.java
  modules/jooby-couchbase/src/main/java/org/jooby/couchbase/CouchbaseSessionStore.java
  modules/jooby-couchbase/src/main/java/org/jooby/couchbase/Datastore.java
  modules/jooby-couchbase/src/main/java/org/jooby/internal/couchbase/AsyncDatastoreImpl.java
  modules/jooby-couchbase/src/main/java/org/jooby/internal/couchbase/DatastoreImpl.java
  modules/jooby-couchbase/src/main/java/org/jooby/internal/couchbase/IdGenerator.java
Labels: tech task

#1157 cleanup jooby-crash
  modules/jooby-crash/src/main/java/org/jooby/crash/CrashBootstrap.java
  modules/jooby-crash/src/main/java/org/jooby/crash/CrashFSDriver.java
  modules/jooby-crash/src/main/java/org/jooby/crash/SimpleProcessContext.java
  modules/jooby-crash/src/main/java/org/jooby/crash/WebShellHandler.java
Labels: tech task

#1158 cleanup-jooby-flyway
  modules/jooby-flyway/src/main/java/org/jooby/flyway/Flywaydb.java
Labels: tech task

#1159 cleanup-jooby-filewatcher
  modules/jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileEventOptions.java
  modules/jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileMonitor.java
  modules/jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileWatcher.java
  modules/jooby-filewatcher/src/main/java/org/jooby/filewatcher/FirstOfPathMatcher.java
Labels: tech task

#1162 cleanup-jooby-hbm
  modules/jooby-hbm/src/main/java/org/jooby/hbm/Hbm.java
  modules/jooby-hbm/src/main/java/org/jooby/internal/hbm/RootUnitOfWork.java
  modules/jooby-hbm/src/main/java/org/jooby/internal/hbm/ScanEnvImpl.java
  modules/jooby-hbm/src/main/java/org/jooby/internal/hbm/SessionProvider.java
  modules/jooby-hbm/src/main/java/org/jooby/internal/hbm/UnitOfWorkProvider.java
Labels: tech task

#1163 cleanup-jooby-undertow
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/ChunkedStream.java
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/LogIoCallback.java
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowHandler.java
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowPush.java
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowRequest.java
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowResponse.java
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowServer.java
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowSse.java
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowUpload.java
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowWebSocket.java
Labels: tech task

#1164 cleanup-jooby-whoops
  modules/jooby-whoops/src/main/java/org/jooby/whoops/SourceLocator.java
  modules/jooby-whoops/src/main/java/org/jooby/whoops/Whoops.java
Labels: tech task

#1165 cleanup-jooby-gson
  modules/jooby-gson/src/main/java/org/jooby/json/GsonParser.java
  modules/jooby-gson/src/main/java/org/jooby/json/GsonRenderer.java
  modules/jooby-gson/src/main/java/org/jooby/json/Gzon.java
Labels: tech task

#1166 cleanup-jooby-spymemcached
  modules/jooby-spymemcached/src/main/java/org/jooby/internal/memcached/MemcachedClientProvider.java
  modules/jooby-spymemcached/src/main/java/org/jooby/memcached/SpySessionStore.java
Labels: tech task

#1167 cleanup-jooby-sitemap
  modules/jooby-sitemap/src/main/java/org/jooby/internal/sitemap/JSitemap.java
  modules/jooby-sitemap/src/main/java/org/jooby/internal/sitemap/SitemapHandler.java
Labels: tech task

#1168 cleanup-jooby-servlet
  modules/jooby-servlet/src/main/java/org/jooby/servlet/ServletServletRequest.java
  modules/jooby-servlet/src/main/java/org/jooby/servlet/ServletUpload.java
Labels: tech task

#1169 cleanup-jooby-scanner
  modules/jooby-scanner/src/main/java/org/jooby/scanner/Scanner.java
Labels: tech task

#1170 cleanup-jooby-gradle-plugin
  modules/jooby-gradle-plugin/src/main/java/org/jooby/run/AssetTask.java
  modules/jooby-gradle-plugin/src/main/java/org/jooby/run/JoobyContainer.java
  modules/jooby-gradle-plugin/src/main/java/org/jooby/run/JoobyProject.java
  modules/jooby-gradle-plugin/src/main/java/org/jooby/run/JoobyTask.java
Labels: tech task

#1171 cleanup-jooby-rxjava
  modules/jooby-rxjava/src/main/java/org/jooby/rx/ExecSchedulerHook.java
  modules/jooby-rxjava/src/main/java/org/jooby/rx/Rx.java
Labels: tech task

#1172 cleanup-jooby-quartz
  modules/jooby-quartz/src/main/java/org/jooby/internal/quartz/JobExpander.java
  modules/jooby-quartz/src/main/java/org/jooby/internal/quartz/MethodJobDetail.java
  modules/jooby-quartz/src/main/java/org/jooby/internal/quartz/QuartzConnectionProvider.java
  modules/jooby-quartz/src/main/java/org/jooby/internal/quartz/ReflectiveJob.java
  modules/jooby-quartz/src/main/java/org/jooby/quartz/Quartz.java
Labels: tech task

#1173 cleanup-jooby-hbv
  modules/jooby-hbv/src/main/java/org/jooby/hbv/Hbv.java
  modules/jooby-hbv/src/main/java/org/jooby/hbv/HbvConstraintValidatorFactory.java
  modules/jooby-hbv/src/main/java/org/jooby/hbv/HbvFactory.java
  modules/jooby-hbv/src/main/java/org/jooby/hbv/HbvParser.java
Labels: tech task

#1174 cleanup-jooby-cassandra
  modules/jooby-cassandra/src/main/java/org/jooby/cassandra/Cassandra.java
  modules/jooby-cassandra/src/main/java/org/jooby/cassandra/CassandraMapper.java
  modules/jooby-cassandra/src/main/java/org/jooby/cassandra/CassandraSessionStore.java
  modules/jooby-cassandra/src/main/java/org/jooby/cassandra/ConnectionString.java
  modules/jooby-cassandra/src/main/java/org/jooby/cassandra/Datastore.java
Labels: tech task

#1175 cleanup-jooby-commons-email
  modules/jooby-commons-email/src/main/java/org/jooby/internal/mail/EmailFactory.java
  modules/jooby-commons-email/src/main/java/org/jooby/internal/mail/HtmlEmailProvider.java
  modules/jooby-commons-email/src/main/java/org/jooby/internal/mail/ImageHtmlEmailProvider.java
  modules/jooby-commons-email/src/main/java/org/jooby/internal/mail/MultiPartEmailProvider.java
  modules/jooby-commons-email/src/main/java/org/jooby/internal/mail/SimpleEmailProvider.java
  modules/jooby-commons-email/src/main/java/org/jooby/mail/CommonsEmail.java
Labels: tech task

#1176 cleanup-jooby-mongodb-rx
  modules/jooby-mongodb-rx/src/main/java/org/jooby/mongodb/MongoRx.java
Labels: tech task

#1177 cleanup-jooby-mongodb
  modules/jooby-mongodb/src/main/java/org/jooby/mongodb/MongoSessionStore.java
Labels: tech task

#1178 cleanup-jooby-hbs
  modules/jooby-hbs/src/main/java/org/jooby/hbs/Hbs.java
  modules/jooby-hbs/src/main/java/org/jooby/internal/hbs/HbsEngine.java
  modules/jooby-hbs/src/main/java/org/jooby/internal/hbs/HbsHelpers.java
Labels: tech task

#1152 cleanup jooby-assets
  modules/jooby-assets/src/main/java/org/jooby/assets/AssetCompiler.java
  modules/jooby-assets/src/main/java/org/jooby/assets/AssetOptions.java
  modules/jooby-assets/src/main/java/org/jooby/assets/Props.java
  modules/jooby-assets/src/main/java/org/jooby/assets/Replace.java
  modules/jooby-assets/src/main/java/org/jooby/internal/assets/AssetVars.java
  modules/jooby-assets/src/main/java/org/jooby/internal/assets/AssetWriter.java
  modules/jooby-assets/src/main/java/org/jooby/internal/assets/LiveCompiler.java
  modules/jooby-assets/src/main/java/org/jooby/internal/assets/Watcher.java
Labels: tech task

#1150 code cleanup jooby-akka
  modules/jooby-akka/pom.xml
  modules/jooby-akka/src/main/java/org/jooby/akka/Akka.java
  modules/jooby-akka/src/test/java/org/jooby/akka/AkkaTest.java
Labels: tech task

#1181 a little more code cleanup
  modules/jooby-bom/bom.groovy
  modules/jooby-jade/src/main/java/org/jooby/jade/Engine.java
  modules/jooby-jdbi/src/main/java/org/jooby/jdbi/Jdbi.java
  modules/jooby-jdbi/src/main/java/org/skife/jdbi/v2/ExpandedStmtRewriter.java
  modules/jooby-run/src/main/java/org/jooby/run/Watcher.java
Labels: tech task
