Repository jooby-project/jooby, pull requests merged in 2019-11, with the labels that each got.

#1414 Bugfix/issue1413
  jooby/src/main/java/io/jooby/CorsHandler.java
Labels: bug, cors

#1415 Bugfix/1413
  jooby/src/main/java/io/jooby/CorsHandler.java
  tests/src/test/java/io/jooby/Issue1413.java
Labels: enhancement

#1412 Remove unused dependency
  jooby/pom.xml
Labels: enhancement

#1389 [v1] Test fixes for windows path separators, line endings
  jooby/src/main/resources/org/jooby/jooby.conf
  jooby/src/test/java/org/jooby/test/JoobyRunner.java
  modules/coverage-report/src/test/java/org/jooby/jackson/JsonCustomMapperFeature.java
  modules/coverage-report/src/test/java/org/jooby/jackson/JsonDoWithFeature.java
  modules/coverage-report/src/test/java/org/jooby/whoops/WhoopsTest.java
  modules/coverage-report/src/test/resources/assets.conf
  modules/jooby-assets-sass/src/test/java/org/jooby/assets/SassTest.java
  modules/jooby-assets-svg-sprites/src/test/java/org/jooby/assets/SvgSpritesFileSetTest.java
  modules/jooby-assets/src/test/java/org/jooby/assets/AssetCompilerTest.java
Labels: build
