Repository jooby-project/jooby, pull requests merged in 2019-04, with the labels that each got.

#1304 Upgrade to Hibernate 5.3.9
  modules/jooby-hbm/pom.xml
  modules/jooby-hbm/src/main/java/org/jooby/hbm/Hbm.java
  modules/jooby-hbm/src/test/java/org/jooby/hbm/HbmTest.java
  pom.xml
Labels: hibernate, version-bump

#1309 Refactored request handler to throw a better exception
  jooby/src/main/java/org/jooby/Request.java
  jooby/src/main/java/org/jooby/internal/RequestImpl.java
  jooby/src/main/java/org/jooby/spi/NativeRequest.java
  jooby/src/test/java/org/jooby/RequestTest.java
  modules/jooby-netty/src/main/java/org/jooby/internal/netty/NettyRequest.java
  modules/jooby-servlet/src/main/java/org/jooby/servlet/ServletServletRequest.java
  modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowRequest.java
Labels: enhancement

#1310 Fix build issue with JDK9 due to outdated dokka-maven-plugin
  modules/jooby-bom/pom.xml
  pom.xml
Labels: version-bump

#1311 Added explicit dependency on crsh-cli to fix maven compilation problem
  modules/jooby-crash/pom.xml
  pom.xml
Labels: bug

#1314 docs did not use ctx.path for path parameters
  docs/asciidoc/routing.adoc
Labels: documentation

#1315 gradle syntax is without colon for compile
  docs/src/main/java/io/jooby/adoc/DependencyProcessor.java
Labels: documentation
