Repository jooby-project/jooby, pull requests merged in 2019-12, with the labels that each got.

#1449 Add SessionRequest decorator in hibernate module
  modules/jooby-hibernate/src/main/java/io/jooby/hibernate/SessionRequest.java
  modules/jooby-hibernate/src/main/java/io/jooby/hibernate/TransactionalRequest.java
Labels: hibernate

#1474 version bump
  pom.xml
Labels: dependencies

#1461 Upgrade to Elasticsearch 7.5.0
  modules/jooby-bom/pom.xml
  pom.xml
Labels: elasticsearch
