Repository jooby-project/jooby, pull requests merged in 2020-11, with the labels that each got.

#2101 Rocker: move from string builder to byte array
  docs/asciidoc/modules/rocker.adoc
  modules/jooby-bom/pom.xml
  modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyContext.java
  modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyHandler.java
  modules/jooby-rocker/src/main/java/io/jooby/rocker/ByteBufferOutput.java
  modules/jooby-rocker/src/main/java/io/jooby/rocker/RockerHandler.java
  modules/jooby-rocker/src/main/java/io/jooby/rocker/RockerMessageEncoder.java
  modules/jooby-rocker/src/main/java/io/jooby/rocker/RockerModule.java
  modules/jooby-rocker/src/main/java/io/jooby/rocker/RockerResponseHandler.java
  modules/jooby-utow/src/main/java/io/jooby/internal/utow/UtowContext.java
  modules/jooby-utow/src/main/java/io/jooby/internal/utow/UtowHandler.java
Labels: performance, rocker

#2108 Logging exceptions occurred at app initialization.
  jooby/src/main/java/io/jooby/Jooby.java
  jooby/src/main/java/io/jooby/exception/StartupException.java
  tests/src/test/java/io/jooby/Issue2107.java
Labels: enhancement

#2119 Update error-handler.adoc [Docs]
  docs/asciidoc/error-handler.adoc
Labels: documentation

#2115 fix typo in Kotlin code example [Scoped Decorator]
  docs/asciidoc/routing.adoc
Labels: documentation

#2116 fix typo in Java example [Static Site]
  docs/asciidoc/static-files.adoc
Labels: documentation

#2133 Jooby.install(Supplier<Jooby>)
  docs/asciidoc/routing.adoc
  jooby/src/main/java/io/jooby/Jooby.java
  jooby/src/main/java/io/jooby/internal/RouterImpl.java
  jooby/src/test/kotlin/io/jooby/Idioms.kt
  jooby/src/test/kotlin/io/jooby/SubApp.kt
  modules/jooby-bom/pom.xml
  modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/ReturnTypeParser.java
  modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/RouteParser.java
  modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/TypeFactory.java
  modules/jooby-openapi/src/test/java/issues/i1905/App1905.java
  modules/jooby-openapi/src/test/java/issues/i1905/Issue1905.java
  modules/jooby-openapi/src/test/java/issues/i1905/SubApp1905.java
  modules/jooby-openapi/src/test/kotlin/kt/i1905/App1905.kt
  modules/jooby-openapi/src/test/kotlin/kt/i1905/Issue1905.kt
  modules/jooby-openapi/src/test/kotlin/kt/i1905/SubApp1905.kt
  tests/src/test/java/io/jooby/i1905/A1905.java
  tests/src/test/java/io/jooby/i1905/AService1905.java
  tests/src/test/java/io/jooby/i1905/B1905.java
  tests/src/test/java/io/jooby/i1905/BService1905.java
  tests/src/test/java/io/jooby/i1905/Issue1905.java
Labels: feature

#2134 Docs corrections related to install op.
  docs/asciidoc/routing.adoc
  jooby/src/main/java/io/jooby/Jooby.java
Labels: documentation

#2136 Add Jasypt module for encrypted properties
  docs/asciidoc/modules/jasypt.adoc
  docs/asciidoc/modules/modules.adoc
  jooby/src/main/java/io/jooby/Environment.java
  modules/jooby-jasypt/pom.xml
  modules/jooby-jasypt/src/main/java/io/jooby/jasypt/JasyptModule.java
  modules/jooby-jasypt/src/test/java/io/jooby/jasypt/JasyptModuleTest.java
  modules/pom.xml
  pom.xml
Labels: jasypt

#2138 openapi/swagger: Conflicting setter definitions for property
  modules/jooby-openapi/pom.xml
  modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/ConflictiveSetter.java
  modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/ParserContext.java
Labels: build
