Repository jooby-project/jooby, pull requests merged in 2020-05, with the labels that each got.

#1678 jackson objectmapper initialisation new syntax
  modules/jooby-jackson/src/main/java/io/jooby/json/JacksonModule.java
Labels: enhancement, jackson

#1689 Mark conf directory as resource directory
  modules/jooby-cli/src/main/resources/cli/pom.xml.hbs
Labels: enhancement

#1717 update undertow version to 2.1.0.Final
  pom.xml
Labels: undertow
