Repository jooby-project/jooby, pull requests merged in 2020-07, with the labels that each got.

#1836 Add import of OpenAPIModule only if --openapi option was specified
  modules/jooby-cli/src/main/resources/cli/App.java.hbs
  modules/jooby-cli/src/main/resources/cli/App.kt.hbs
Labels: bug, jooby-cli

#1841 Extension: commons-email from Jooby 1.x
  modules/jooby-bom/pom.xml
  modules/jooby-commons-email/pom.xml
  modules/jooby-commons-email/src/main/java/io/jooby/email/CommonsEmailModule.java
  modules/jooby-commons-email/src/main/java/io/jooby/internal/email/EmailFactory.java
  modules/jooby-commons-email/src/main/java/io/jooby/internal/email/HtmlEmailProvider.java
  modules/jooby-commons-email/src/main/java/io/jooby/internal/email/ImageHtmlEmailProvider.java
  modules/jooby-commons-email/src/main/java/io/jooby/internal/email/MultiPartEmailProvider.java
  modules/jooby-commons-email/src/main/java/io/jooby/internal/email/SimpleEmailProvider.java
  modules/pom.xml
  pom.xml
Labels: feature

#1879 fixed issue with pebble's allowUnsafeMethods option
  modules/jooby-pebble/src/main/java/io/jooby/pebble/PebbleModule.java
Labels: pebble

#1876 Print "forcibly closed by the remote host" message on debug level only
  jooby/src/main/java/io/jooby/Server.java
Labels: enhancement

#1849 Asm support for java 11
  jooby/src/main/java/org/jooby/internal/RouteMetadata.java
  modules/jooby-apitool/src/main/java/org/jooby/internal/apitool/TypeDescriptorParser.java
  modules/jooby-bom/pom.xml
  pom.xml
Labels: enhancement
