Repository jooby-project/jooby, pull requests merged in 2020-06, with the labels that each got.

#1767 Fixed invalid module name being used for MVC reflection fallback
  jooby/src/main/java/io/jooby/Jooby.java
Labels: bug, mvc

#1770 make message encoder return type nullable to prevent kotlin's compila…
  jooby/src/main/java/io/jooby/MessageEncoder.java
Labels: bug, kotlin

#1791 Fix usage of javax.annotation.Nonnull on String args in MVC routes
  modules/jooby-apt/src/main/java/io/jooby/internal/apt/ParamDefinition.java
  modules/jooby-apt/src/test/java/source/Controller1786.java
  modules/jooby-apt/src/test/java/tests/Issue1786.java
Labels: bug

#1802 Add note about Maven GAV and modules
  docs/asciidoc/migration.adoc
Labels: documentation

#1819 Docs: currentTimeInMillis() -> currentTimeMillis()
  docs/asciidoc/routing.adoc
Labels: documentation
