Repository jooby-project/jooby, pull requests merged in 2021-12, with the labels that each got.

#2448 Fix OpenAPI generation for newer Kotlin compiler and support java.time types
  jooby/src/main/kotlin/io/jooby/Kooby.kt
  modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/AnnotationParser.java
  modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/ParserContext.java
Labels: bug, kotlin, openapi

#2468 Do not override config origins
  jooby/src/main/java/io/jooby/Environment.java
  jooby/src/test/java/io/jooby/EnvironmentTest.java
Labels: enhancement

#2445 Upgrade to Hibernate 5.5.7 for best Java 17 support
  pom.xml
Labels: hibernate, dependencies

#2489 Update log4j 2.17.0 to 2.17.1
  pom.xml
Labels: dependencies
