Repository jooby-project/jooby, pull requests merged in 2023-10, with the labels that each got.

#3171 Cleaned up "Getting Started" docs
  docs/asciidoc/getting-started.adoc
Labels: documentation

#3183 📖 Cleaned up Introduction docs
  docs/asciidoc/index.adoc
Labels: documentation

#3196 Bump ASM from 9.3 to 9.6 to enable support for Java 21
  pom.xml
Labels: 2.x

#3201 Add io.jooby.jackson to Package rename in Upgrade documentation
  docs/asciidoc/migration/3.x.adoc
Labels: jackson, documentation, migration-3

#3199 Cleanup starting and dagger docs
  docs/asciidoc/di-dagger.adoc
  docs/asciidoc/getting-started.adoc
Labels: documentation

#3198 Add Avaje-Inject to DI docs
  docs/asciidoc/dependency-injection.adoc
  docs/asciidoc/di-avaje.adoc
Labels: documentation, dependency-injection

#3204 use graphQLContext instead of context
  modules/jooby-graphql/src/main/java/io/jooby/internal/graphql/GraphQLHandler.java
Labels: enhancement, graphql
