Repository jooby-project/jooby, pull requests merged in 2025-05, with the labels that each got.

#3646 feature: support multiple application on single server
  docs/asciidoc/problem-details.adoc
  docs/asciidoc/routing.adoc
  docs/pom.xml
  docs/src/main/java/io/jooby/adoc/DocGenerator.java
  docs/src/main/java/io/jooby/adoc/JavadocProcessor.java
  jooby/src/main/java/io/jooby/Context.java
  jooby/src/main/java/io/jooby/Jooby.java
  jooby/src/main/java/io/jooby/LoggingService.java
  jooby/src/main/java/io/jooby/Router.java
  jooby/src/main/java/io/jooby/Server.java
  jooby/src/main/java/io/jooby/internal/MutedServer.java
  modules/jooby-jetty/src/main/java/io/jooby/internal/jetty/PrefixHandler.java
  modules/jooby-jetty/src/main/java/io/jooby/jetty/JettyServer.java
  modules/jooby-kotlin/src/main/kotlin/io/jooby/kt/Kooby.kt
  modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyContext.java
  modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyHandler.java
  modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyPipeline.java
  modules/jooby-netty/src/main/java/io/jooby/netty/NettyServer.java
  modules/jooby-test/src/main/java/io/jooby/test/JoobyExtension.java
  modules/jooby-undertow/src/main/java/io/jooby/internal/undertow/UndertowHandler.java
  modules/jooby-undertow/src/main/java/io/jooby/undertow/UndertowServer.java
  tests/src/test/java/examples/MultiApp.java
  tests/src/test/java/examples/multiapp/BarApp.java
  tests/src/test/java/examples/multiapp/BarService.java
  tests/src/test/java/examples/multiapp/FooApp.java
  tests/src/test/java/examples/multiapp/FooService.java
  tests/src/test/java/io/jooby/junit/ServerExtensionImpl.java
  tests/src/test/java/io/jooby/junit/ServerTestRunner.java
  tests/src/test/kotlin/KtMultiApp.kt
Labels: feature

#3651 Fix documentation for Custom environment
  docs/asciidoc/configuration.adoc
Labels: documentation

#3681 drop unused property
  pom.xml
Labels: build
